services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    labels:
      - wud.watch.digest=true
      - wud.link.template=https://github.com/dani-garcia/vaultwarden/releases
    environment:
      - DOMAIN=https://vaultwarden.motaphe.dev
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
    volumes:
      - ./vw-data/:/data/
    ports:
      - "8000:80"
